#!/usr/bin/env python3
"""Custom tech generator — turns a description of an image (or a pasted compose
service) into a stack directory the CLI and console both understand.

Used two ways:
  - imported by the console (app.py) for the web form
  - run as a CLI inside the console image by `infrapack add`, so the host
    needs no Python:

      stackgen.py add NAME --image redis:7 --port 6379 [--port 8080:80]
                    [--volume /data] [--env K=V] [--command "..."]
                    [--healthcheck "cmd"] [--ui-image IMG --ui-port P ...]
      stackgen.py add NAME --compose -          # a compose file on stdin
      stackgen.py add NAME --json -             # a spec object on stdin

Every host port becomes a <NAME>_PORT setting, every image tag a
<NAME>_VERSION setting, so custom techs are editable like catalog ones.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import registry as reg  # noqa: E402

PROJECT = "infrapack"
STACK_NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,23}$")
IMAGE_RE = re.compile(r"^[a-z0-9][a-z0-9._/-]{0,127}$")
TAG_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
VOLPATH_RE = re.compile(r"^/[A-Za-z0-9._/-]{0,127}$")
ENV_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
RESERVED = {"console", "all", "infra", "infrapack"}


class SpecError(ValueError):
    """A message meant for the user."""


def env_prefix(stack):
    return stack.upper().replace("-", "_")


def _yaml_str(value):
    return json.dumps(str(value))     # JSON strings are valid YAML double-quoted scalars


def _yaml_service(name, spec):
    lines = [f"  {name}:",
             f'    image: "{spec["image"]}:${{{spec["tag_var"]}:-{spec["tag"]}}}"',
             f"    container_name: {PROJECT}-{name}",
             "    restart: *restart"]
    if spec.get("platform"):
        lines.append(f"    platform: {spec['platform']}")
    if spec.get("user"):
        lines.append(f"    user: {_yaml_str(spec['user'])}")
    if spec.get("command"):
        cmd = spec["command"]
        if isinstance(cmd, list):
            lines.append(f"    command: [{', '.join(_yaml_str(c) for c in cmd)}]")
        else:
            lines.append(f"    command: {_yaml_str(cmd)}")
    if spec.get("entrypoint"):
        ep = spec["entrypoint"]
        lines.append(f"    entrypoint: [{', '.join(_yaml_str(c) for c in (ep if isinstance(ep, list) else [ep]))}]")
    if spec.get("env"):
        lines.append("    environment:")
        for k, v in spec["env"].items():
            lines.append(f"      {k}: {_yaml_str(v)}")
    if spec.get("ports"):
        lines.append("    ports:")
        for host_var, host_default, container in spec["ports"]:
            lines.append(f'      - "${{{host_var}:-{host_default}}}:{container}"')
    if spec.get("volumes"):
        lines.append("    volumes:")
        for vol_name, path in spec["volumes"]:
            lines.append(f"      - {vol_name}:{path}")
    if spec.get("healthcheck"):
        test = ", ".join(_yaml_str(part) for part in spec["healthcheck"])
        lines += ["    healthcheck:", f"      test: [{test}]",
                  "      interval: 10s", "      timeout: 5s",
                  "      retries: 12", "      start_period: 20s"]
    if spec.get("depends_on"):
        lines += ["    depends_on:"] + [f"      - {d}" for d in spec["depends_on"]]
    lines.append("    networks: [infra]")
    return "\n".join(lines)


def render_compose(spec):
    yml = [f"# {spec['label']} — custom tech, generated by InfraPack.",
           "# Safe to edit by hand; `infrapack up` picks changes up.",
           "",
           "x-restart: &restart ${INFRA_RESTART:-no}",
           "",
           "services:"]
    vols = []
    for svc in spec["compose_services"]:
        yml.append(_yaml_service(svc["name"], svc))
        yml.append("")
        vols += [v for v, _ in svc.get("volumes", [])]
    if vols:
        yml.append("volumes:")
        yml += [f"  {v}:" for v in vols]
        yml.append("")
    return "\n".join(yml)


def write_stack(spec):
    d = reg.STACKS_DIR / spec["stack"]
    d.mkdir(parents=True, exist_ok=True)
    (d / "compose.yml").write_text(render_compose(spec))
    (d / "stack.json").write_text(json.dumps(spec["meta"], indent=2) + "\n")
    (d / "defaults.env").write_text("".join(f"{k}={v}\n" for k, v in spec["env"].items()))
    return d


# ------------------------------------------------------------------ spec ---
def _split_image(ref):
    """'redis:7-alpine' -> ('redis', '7-alpine'); registry ports are handled."""
    ref = str(ref or "").strip().lower()
    if "@" in ref:
        raise SpecError("digest references are not supported; use a tag")
    name, tag = ref, "latest"
    last = ref.rsplit("/", 1)[-1]
    if ":" in last:
        name, tag = ref.rsplit(":", 1)
    if not IMAGE_RE.match(name):
        raise SpecError(f"image '{name}' is not a valid image name")
    if not TAG_RE.match(tag):
        raise SpecError(f"tag '{tag}' is not a valid tag")
    return name, tag


def _parse_port(item):
    """6379 | 8080:80 | {'host':.., 'container':..} -> (host, container)."""
    if isinstance(item, dict):
        host, cont = item.get("host"), item.get("container") or item.get("host")
    else:
        text = str(item).strip()
        host, _, cont = text.partition(":")
        cont = cont or host
    try:
        host, cont = int(host), int(cont)
    except (TypeError, ValueError):
        raise SpecError(f"port '{item}' must look like 6379 or 8080:80")
    for n in (host, cont):
        if not 1 <= n <= 65535:
            raise SpecError("ports must be between 1 and 65535")
    return host, cont


def _parse_env(value):
    """dict, list of K=V, or a multi-line string of K=V."""
    if not value:
        return {}
    if isinstance(value, dict):
        items = value.items()
    else:
        lines = value if isinstance(value, list) else str(value).splitlines()
        items = []
        for line in lines:
            line = str(line).strip()
            if not line or line.startswith("#"):
                continue
            k, _, v = line.partition("=")
            items.append((k.strip(), v.strip()))
    out = {}
    for k, v in items:
        if not ENV_KEY_RE.match(str(k)):
            raise SpecError(f"'{k}' is not a valid environment variable name")
        out[str(k)] = "" if v is None else str(v)
    return out


def build_spec(body, existing=None):
    """Validate a request and turn it into something render_compose can write.

    body: {name, label?, blurb?, category?, core: {...}, ui?: {...}} where each
    service part is {image, tag?, ports|port, container_port?, volumes|volume,
    env, command, healthcheck, facts?, desc?, label?, link_port?}.
    """
    stack = str(body.get("name", "")).strip().lower()
    if not STACK_NAME_RE.match(stack):
        raise SpecError("name must be lowercase letters, digits and dashes (2-24 chars)")
    taken = existing if existing is not None else {s["stack"] for s in reg.load_all()}
    if stack in RESERVED or stack in taken:
        raise SpecError(f"'{stack}' already exists")

    label = str(body.get("label") or stack.title()).strip()[:40] or stack.title()
    pre = env_prefix(stack)
    env_defaults, settings, meta_services, compose_services = {}, [], [], []

    def add_service(part, name, role):
        """role: 'core' | 'ui' | 'extra'"""
        image, tag = _split_image(part.get("image") if not part.get("tag") else f"{part['image']}:{part['tag']}")
        suffix = "" if role == "core" else ("_UI" if role == "ui" else "_" + env_prefix(name[len(stack) + 1:]))
        group = part.get("label") or (label if role == "core" else f"{label} {name[len(stack) + 1:].title()}")
        tag_var = f"{pre}{suffix}_VERSION"
        env_defaults[tag_var] = tag
        settings.append({"key": tag_var, "label": "Image tag", "type": "text", "group": group})

        port_items = list(part.get("ports") or [])
        if part.get("port"):
            port_items.insert(0, {"host": part["port"], "container": part.get("container_port") or part["port"]})
        ports = []
        for i, item in enumerate(port_items):
            host, cont = _parse_port(item)
            var = f"{pre}{suffix}_PORT" if i == 0 else f"{pre}{suffix}_PORT{i + 1}"
            env_defaults[var] = str(host)
            settings.append({"key": var, "label": "Port" if i == 0 else f"Port {i + 1} (→{cont})",
                             "type": "port", "group": group})
            ports.append((var, host, cont))

        env = {k: v.replace("{NAME}", stack) for k, v in _parse_env(part.get("env")).items()}

        vol_paths = list(part.get("volumes") or [])
        if part.get("volume"):
            vol_paths.insert(0, part["volume"])
        volumes = []
        for i, path in enumerate(vol_paths):
            path = str(path).strip()
            if not path:
                continue
            if not VOLPATH_RE.match(path):
                raise SpecError(f"volume path '{path}' must be an absolute path inside the container")
            volumes.append((f"{name}-data" if i == 0 else f"{name}-data{i + 1}", path))

        hc = part.get("healthcheck")
        if hc and not isinstance(hc, list):
            hc = ["CMD-SHELL", str(hc)]

        svc = {"name": name, "image": image, "tag": tag, "tag_var": tag_var,
               "ports": ports, "env": env, "volumes": volumes,
               "command": part.get("command") or None, "entrypoint": part.get("entrypoint") or None,
               "user": part.get("user") or None, "platform": part.get("platform") or None,
               "healthcheck": hc,
               "depends_on": [d for d in (part.get("depends_on") or []) if d != name]}
        if role != "core" and not svc["depends_on"]:
            svc["depends_on"] = [stack]
        compose_services.append(svc)

        main_port = ports[0] if ports else None
        subs = {"{PORT}": f"{{{main_port[0]}}}" if main_port else "", "{NAME}": stack,
                "{TAGVAR}": f"{{{tag_var}}}"}
        facts = []
        for f in part.get("facts") or []:
            value = str(f.get("value", ""))
            for k, v in subs.items():
                value = value.replace(k, v)
            facts.append(dict(f, value=value))
        if not facts:
            for var, host, cont in ports:
                facts.append({"label": "Host" if var == (main_port or [None])[0] else f"Port {cont}",
                              "value": f"localhost:{{{var}}}", "copy": True})
            if ports:
                facts.append({"label": "In-network", "value": f"{name}:{ports[0][2]}", "copy": True})
            for k, v in env.items():
                if re.search(r"(PASS|SECRET|TOKEN|KEY)", k, re.I):
                    facts.append({"label": k, "value": v, "copy": True, "secret": True})
                elif re.search(r"(USER|DB|DATABASE|NAME)$", k, re.I):
                    facts.append({"label": k, "value": v, "copy": True})
        entry = {"name": name, "label": part.get("label") or (label if role == "core" else name),
                 "facts": facts,
                 "desc": str(part.get("desc") or f"{image}:{{{tag_var}}}").replace("{TAGVAR}", f"{{{tag_var}}}")[:120]}
        if role == "ui":
            entry["ui"] = True
            if main_port:
                entry["link"] = f"http://localhost:{{{main_port[0]}}}"
        elif part.get("link_port"):
            var = next((v for v, h, c in ports if str(c) == str(part["link_port"])), None)
            if var:
                entry["link"] = f"http://localhost:{{{var}}}"
        meta_services.append(entry)

    core = body.get("core") or {}
    if not core.get("image"):
        raise SpecError("an image is required")
    add_service(core, stack, "core")
    ui = body.get("ui")
    if ui and ui.get("image"):
        add_service(ui, f"{stack}-ui", "ui")
    for extra in body.get("extras") or []:
        sub = str(extra.get("name", "")).strip().lower()
        if not re.match(r"^[a-z0-9-]{1,20}$", sub):
            raise SpecError(f"extra service name '{sub}' is not valid")
        add_service(extra, f"{stack}-{sub}", "extra")

    meta = {"stack": stack, "label": label, "custom": True,
            "blurb": str(body.get("blurb") or core.get("desc") or f"custom · {core.get('image')}")[:120],
            "category": str(body.get("category") or "custom")[:24],
            "services": meta_services, "settings": settings}
    return {"stack": stack, "label": label, "meta": meta,
            "compose_services": compose_services, "env": env_defaults}


# --------------------------------------------------------- compose import --
def normalise_compose(text):
    """Validate a pasted compose file (or a bare service block) with
    `docker compose config` and return its services as plain dicts."""
    text = text.strip()
    if not text:
        raise SpecError("nothing to import")
    if not re.search(r"^services:\s*$", text, re.M):
        # a bare "name:\n  image: ..." block, or just the body of one service
        if re.match(r"^\s+", text) or re.match(r"^(image|ports|environment|command|volumes):", text):
            text = "services:\n  app:\n" + "\n".join("    " + line for line in text.splitlines())
        else:
            text = "services:\n" + "\n".join("  " + line for line in text.splitlines())
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "compose.yml"
        path.write_text(text)
        try:
            p = subprocess.run(["docker", "compose", "-f", str(path), "--project-name", "import",
                                "config", "--format", "json", "--no-interpolate", "--no-path-resolution"],
                               capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise SpecError(f"could not run docker compose: {exc}")
    if p.returncode != 0:
        msg = (p.stderr or p.stdout).strip().splitlines()
        raise SpecError("not a valid compose file: " + (msg[-1] if msg else "unknown error"))
    try:
        data = json.loads(p.stdout)
    except json.JSONDecodeError:
        raise SpecError("docker compose returned something unexpected")
    services = data.get("services") or {}
    if not services:
        raise SpecError("no services found")
    return services


def _hc_from_compose(hc):
    if not hc or hc.get("disable"):
        return None
    test = hc.get("test")
    if isinstance(test, str):
        return ["CMD-SHELL", test]
    if isinstance(test, list) and test:
        return [str(t) for t in test]
    return None


def spec_from_compose(name, text, label=None):
    """Map normalised compose services onto a build_spec body.
    Named volumes and bind mounts become InfraPack-managed named volumes."""
    services = normalise_compose(text)
    order = list(services)
    # the core is the first service, or the one others depend on most
    scores = {s: 0 for s in order}
    for s, svc in services.items():
        deps = svc.get("depends_on") or {}
        for d in (deps if isinstance(deps, (list, dict)) else []):
            if d in scores:
                scores[d] += 1
    core_name = max(order, key=lambda s: (scores[s], -order.index(s)))

    def part(svc_name, svc):
        ports = []
        for p in svc.get("ports") or []:
            if isinstance(p, dict):
                host, cont = p.get("published"), p.get("target")
            else:
                host, _, cont = str(p).partition(":")
                cont = cont or host
            if host and cont:
                ports.append({"host": str(host).split(":")[-1], "container": str(cont).split("/")[0]})
        vols = []
        for v in svc.get("volumes") or []:
            target = v.get("target") if isinstance(v, dict) else str(v).split(":")[1 if ":" in str(v) else 0]
            if target and target.startswith("/") and "docker.sock" not in target:
                vols.append(target)
        env = svc.get("environment") or {}
        if isinstance(env, list):
            env = dict(e.partition("=")[::2] for e in env)
        deps = svc.get("depends_on") or {}
        deps = list(deps) if isinstance(deps, (list, dict)) else []
        return {"image": svc.get("image"), "ports": ports, "volumes": vols, "env": env,
                "command": svc.get("command"), "entrypoint": svc.get("entrypoint"),
                "user": svc.get("user"), "platform": svc.get("platform"),
                "healthcheck": _hc_from_compose(svc.get("healthcheck")),
                "depends_on": [f"{name}-{d}" if d != core_name else name for d in deps],
                "label": svc_name}

    body = {"name": name, "label": label or name.title(), "core": part(core_name, services[core_name]),
            "extras": [], "blurb": f"imported · {', '.join(order)}"}
    body["core"]["label"] = body["label"] if core_name == "app" else core_name
    for s in order:
        if s == core_name:
            continue
        p = part(s, services[s])
        if s.endswith("-ui") or s == "ui" or s.endswith("ui") and not body.get("ui"):
            body["ui"] = p
        else:
            body["extras"].append(dict(p, name=re.sub(r"[^a-z0-9-]", "-", s.lower())[:20]))
    if not body["core"].get("image"):
        raise SpecError(f"service '{core_name}' has no image (build: is not supported)")
    return body


# ------------------------------------------------------------------- CLI ---
def _parse_args(argv):
    ap = argparse.ArgumentParser(prog="infrapack add", description="define a custom tech from any image")
    ap.add_argument("name", help="lowercase name, e.g. my-queue")
    ap.add_argument("--label", help="display name")
    ap.add_argument("--image", help="image[:tag], e.g. redis:7-alpine")
    ap.add_argument("--port", action="append", default=[], help="HOST[:CONTAINER], repeatable")
    ap.add_argument("--volume", action="append", default=[], help="path inside the container to persist, repeatable")
    ap.add_argument("--env", action="append", default=[], help="KEY=VALUE, repeatable")
    ap.add_argument("--command", help="command override")
    ap.add_argument("--healthcheck", help="shell command that exits 0 when healthy")
    ap.add_argument("--ui-image", help="a web UI image[:tag] to run beside it")
    ap.add_argument("--ui-port", action="append", default=[], help="HOST[:CONTAINER] for the UI, repeatable")
    ap.add_argument("--ui-env", action="append", default=[], help="KEY=VALUE for the UI, repeatable")
    ap.add_argument("--compose", help="import a compose file instead ('-' = stdin)")
    ap.add_argument("--json", help="a spec object ('-' = stdin); used by the console")
    ap.add_argument("--dry-run", action="store_true", help="print the generated compose.yml and exit")
    return ap.parse_args(argv)


def main(argv):
    if len(argv) > 1 and argv[1] == "add":
        argv = argv[1:]
    a = _parse_args(argv[1:])
    try:
        if a.json:
            raw = sys.stdin.read() if a.json == "-" else Path(a.json).read_text()
            body = json.loads(raw)
            body.setdefault("name", a.name)
        elif a.compose:
            text = sys.stdin.read() if a.compose == "-" else Path(a.compose).read_text()
            body = spec_from_compose(a.name, text, a.label)
        else:
            if not a.image:
                raise SpecError("--image is required (or --compose / --json)")
            body = {"name": a.name, "label": a.label,
                    "core": {"image": a.image, "ports": a.port, "volumes": a.volume, "env": a.env,
                             "command": a.command, "healthcheck": a.healthcheck}}
            if a.ui_image:
                body["ui"] = {"image": a.ui_image, "ports": a.ui_port, "env": a.ui_env,
                              "label": f"{a.label or a.name.title()} UI"}
        spec = build_spec(body)
        if a.dry_run:
            print(render_compose(spec))
            print("# defaults.env:")
            for k, v in spec["env"].items():
                print(f"# {k}={v}")
            return 0
        d = write_stack(spec)
        print(json.dumps({"ok": True, "stack": spec["stack"], "dir": str(d), "env": spec["env"]}))
        return 0
    except SpecError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}))
        return 2
    except (OSError, json.JSONDecodeError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}))
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
